"""Maze generation wrapper for the game.

Adapts the external ``mazegenerator`` (A-Maze-ing) package's maze to the
game's needs by populating it with pacgums, super-pacgums, and ghosts.
"""

from mazegenerator import MazeGenerator

from models import Ghost, Pacgum


class MazeGen(MazeGenerator):
    """A maze generated by the A-Maze-ing package, enriched with entities."""

    def __init__(
        self,
        size: tuple[int, int] = (15, 15),
        perfect: bool = False,
        entry_cell: tuple[int, int] = (0, 0),
        exit_cell: tuple[int, int] = (-1, -1),
        seed: int = 0,
    ) -> None:
        """Generate the maze and populate it with pacgums and ghosts.

        Args:
            size: The ``(width, height)`` of the maze.
            perfect: Whether the maze should be a "perfect" maze (no
                loops). Set to ``False`` for Pac-Man-compatible corridors.
            entry_cell: The maze cell used as the entry point.
            exit_cell: The maze cell used as the exit point.
            seed: Random seed used to generate the maze deterministically.
        """
        super().__init__(size, perfect, entry_cell, exit_cell, seed)
        self.pacgums_nb = 0
        self.pacgums: list[Pacgum]
        self.pacgumsInit()
        self.ghosts: list[Ghost]
        self.ghostsInit()

    def pacgumsInit(self) -> None:
        """Fill the maze with pacgums, placing super-pacgums in corners.

        Every open cell receives a pacgum, except the four corners of
        the maze, which each receive a super-pacgum instead.
        """
        self.pacgums = []
        for y in range(self._height):
            for x in range(self._width):
                if self.maze[y][x] == 15:
                    continue
                if y == 0 and x == 0:
                    self.pacgums.append(Pacgum(x, y, super=True))
                elif y == 0 and x == self._width - 1:
                    self.pacgums.append(Pacgum(x, y, super=True))
                elif y == self._height - 1 and x == 0:
                    self.pacgums.append(Pacgum(x, y, super=True))
                elif y == self._height - 1 and x == self._width - 1:
                    self.pacgums.append(Pacgum(x, y, super=True))
                else:
                    self.pacgums.append(Pacgum(x, y))
                self.pacgums_nb += 1

    def ghostsInit(self) -> None:
        """Spawn the four ghosts, one in each corner of the maze."""
        self.ghosts = []
        self.ghosts.append(Ghost(1, 0, "Blinky"))
        self.ghosts.append(Ghost(self._width - 2, 0, "Pinky"))
        self.ghosts.append(Ghost(1, self._height - 1, "Inky"))
        self.ghosts.append(Ghost(self._width - 2, self._height - 1, "Clyde"))
